### PR TITLE
f(initial_spec) basic required functions

### LINKED ISSUE #1: PID SPEC
- [x] SET gains
- [x] Calculate function
- [x] keep track of previous errors for each class instance
- [x] Safe integration and eliminating bias

### PR DESCRIPTION
**Pull request by SammyOina**

### CODE REVIEW

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Structure it as a library for example https://github.com/0804robot/driver/pull/3

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Remove `.vscode`

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Remove `platform.ini`

**Review by rodneyosodo — APPROVED** [review]

**Review by kimanimichael — COMMENTED** [review]
lgtm

**Review by kimanimichael — APPROVED** [review]

**Pull request merged**
